### PR TITLE
Add proper napari dock widget plugin

### LINKED ISSUE #4: make napari plugin
Currently affinder is a standalone function. It should also provide a napari dock widget hook implementation so that napari users can install it.

### PR DESCRIPTION
**Pull request by jni**
Closes #4

This is still WIP.

### CODE REVIEW

**Comment by jni** [comment]
I was running into https://github.com/napari/napari/issues/2116 with the napari import at the top, so I switched to string type annotations, but now I get an error from magicgui, "ValueError: could not pick widget for type:"  (it is blank after that).

**Comment by jni** [comment]
CC @sofroniewn @tlambert03

**Comment by jni** [comment]
Here's the full traceback from the plugin errors dialog:

```pytb
=========================== Errors for plugin 'affinder' ===========================

  napari version: 0.4.4.dev6+g2d570b94


ERROR #1:  Error while importing module affinder.plugin --------------------------

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/miniconda3/envs/all/lib/python3.8/site-packages/napari_plugin_engine/manager.py in _load_and_register(self=<napari_plugin_engine.manager.PluginManager object>, mod_name='affinder.plugin', plugin_name='affinder')
    291         try:
--> 292             module = load(mod_name)
        module = undefined
        global load = <function load at 0x7f441433b310>
        mod_name = 'affinder.plugin'
    293             if self.is_registered(module):

~/miniconda3/envs/all/lib/python3.8/site-packages/napari_plugin_engine/manager.py in load(value='affinder.plugin')
   1004         raise ValueError(f"malformed entry point string: {value}")
-> 1005     module = importlib.import_module(match.group('module'))
        module = undefined
        global importlib.import_module = <function import_module at 0x7f44468d5e50>
        match.group = <built-in method group of re.Match object at 0x7f440487c870>
   1006     attrs = filter(None, (match.group('attr') or '').split('.'))

~/miniconda3/envs/all/lib/python3.8/importlib/__init__.py in import_module(name='affinder.plugin', package=None)
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
        global _bootstrap._gcd_import = <function _gcd_import at 0x7f4446a0b430>
        name = 'affinder.plugin'
        level = 0
        package = None
    128 

~/miniconda3/envs/all/lib/python3.8/importlib/_bootstrap.py in _gcd_import(name='affinder.plugin', package=None, level=0)

~/miniconda3/envs/all/lib/python3.8/importlib/_bootstrap.py in _find_and_load(name='affinder.plugin', import_=<function _gcd_import>)

~/miniconda3/envs/all/lib/python3.8/importlib/_bootstrap.py in _find_and_load_unlocked(name='affinder.plugin', import_=<function _gcd_import>)

~/miniconda3/envs/all/lib/python3.8/importlib/_bootstrap.py in _load_unlocked(spec=ModuleSpec(name='affinder.plugin', loader=<_froz...'/home/jni/projects/affinder/affinder/plugin.py'))

~/miniconda3/envs/all/lib/python3.8/importlib/_bootstrap_external.py in exec_module(self=<_frozen_importlib_external.SourceFileLoader object>, module=<module 'affinder.plugin' from '/home/jni/projects/affinder/affinder/plugin.py'>)

~/miniconda3/envs/all/lib/python3.8/importlib/_bootstrap.py in _call_with_frames_removed(f=<built-in function exec>, *args=(<code object <module> at 0x7f440487eb30, file "/...ni/projects/affinder/affinder/plugin.py", line 1>, {'__builtins__': {'ArithmeticError': <class 'ArithmeticError'>, 'AssertionError': <class 'AssertionError'>, 'AttributeError': <class 'AttributeError'>, 'BaseException': <class 'BaseException'>, 'BlockingIOError': <class 'BlockingIOError'>, 'BrokenPipeError': <class 'BrokenPipeError'>, 'BufferError': <class 'BufferError'>, 'BytesWarning': <class 'BytesWarning'>, 'ChildProcessError': <class 'ChildProcessError'>, 'ConnectionAbortedError': <class 'ConnectionAbortedError'>, ...}, '__cached__': '/home/jni/projects/affinder/affinder/__pycache__/plugin.cpython-38.pyc', '__doc__': None, '__file__': '/home/jni/projects/affinder/affinder/plugin.py', '__loader__': <_frozen_importlib_external.SourceFileLoader object>, '__name__': 'affinder.plugin', '__package__': 'affinder', '__spec__': ModuleSpec(name='affinder.plugin', loader=<_froz...'/home/jni/projects/affinder/affinder/plugin.py'), 'napari_hook_implementation': <napari_plugin_engine.markers.HookImplementationMarker object>}), **kwds={})

~/projects/affinder/affinder/plugin.py in <module>
      1 from napari_plugin_engine import napari_hook_implementation
----> 2 from .affinder import start_affinder
        global affinder = undefined
        global start_affinder = undefined
      3 

~/projects/affinder/affinder/affinder.py in <module>
     70         )
---> 71 def start_affinder(
        global start_affinder = undefined
        global reference = undefined
        global moving = undefined
        global model = undefined
        global AffineTransformChoices = <enum 'AffineTransformChoices'>
        global viewer = undefined
     72         reference: 'napari.layers.Image',

~/miniconda3/envs/all/lib/python3.8/site-packages/magicgui/function_gui.py in inner_func(func=<function start_affinder>)
    354     def inner_func(func: Callable) -> FunctionGui:
--> 355         func_gui = FunctionGui(
        func_gui = undefined
        global FunctionGui = <class 'magicgui.function_gui.FunctionGui'>
        global function = undefined
        func = <function start_affinder at 0x7f43fec8cc10>
        global call_button = undefined
        global layout = undefined
        global labels = undefined
        global param_options = undefined
        global auto_call = undefined
        global result_widget = undefined
        global app = undefined
    356             function=func,

~/miniconda3/envs/all/lib/python3.8/site-packages/magicgui/function_gui.py in __init__(self=UNRECOVERABLE REPR FAILURE, function=<function start_affinder>, call_button='Start', layout='vertical', labels=True, app=None, show=False, auto_call=False, result_widget=False, param_options={'viewer': {'label': ' ', 'visible': False}}, name=None, **kwargs={})
     81             labels=labels,
---> 82             widgets=list(sig.widgets(app).values()),
        global widgets = undefined
        global list = undefined
        sig.widgets = <bound method MagicSignature.widgets of <MagicSignature (reference: ForwardRef('napari.layers.Image'), moving: ForwardRef('napari.layers.Image'), model: affinder.affinder.AffineTransformChoices, viewer: ForwardRef('napari.viewer.Viewer'))>>
        app.values = undefined
     83             return_annotation=sig.return_annotation,

~/miniconda3/envs/all/lib/python3.8/site-packages/magicgui/signature.py in widgets(self=<MagicSignature (reference: ForwardRef('napari.l...ces, viewer: ForwardRef('napari.viewer.Viewer'))>, app=None)
    220         return MappingProxyType(
--> 221             {n: p.to_widget(app) for n, p in self.parameters.items()}
        global n = undefined
        global p.to_widget = undefined
        app = None
        global p = undefined
        self.parameters.items = <built-in method items of mappingproxy object at 0x7f43f7ac64f0>
    222         )

~/miniconda3/envs/all/lib/python3.8/site-packages/magicgui/signature.py in <dictcomp>(.0=<odict_iterator object>)
    220         return MappingProxyType(
--> 221             {n: p.to_widget(app) for n, p in self.parameters.items()}
        n = 'reference'
        p.to_widget = <bound method MagicParameter.to_widget of <MagicParameter "reference: ForwardRef('napari.layers.Image')" {}>>
        global app = undefined
        p = <MagicParameter "reference: ForwardRef('napari.layers.Image')" {}>
        global self.parameters.items = undefined
    222         )

~/miniconda3/envs/all/lib/python3.8/site-packages/magicgui/signature.py in to_widget(self=<MagicParameter "reference: ForwardRef('napari.layers.Image')" {}>, app=None)
    137         annotation, options = split_annotated_type(self.annotation)
--> 138         widget = create_widget(
        widget = undefined
        create_widget = <function create_widget at 0x7f4414404e50>
        global name = undefined
        self.name = 'reference'
        value = None
        annotation = ForwardRef('napari.layers.Image')
        app = None
        options = {}
    139             name=self.name,

~/miniconda3/envs/all/lib/python3.8/site-packages/magicgui/widgets/_bases.py in create_widget(value=None, annotation=ForwardRef('napari.layers.Image'), name='reference', param_kind='POSITIONAL_OR_KEYWORD', label=None, gui_only=False, app=None, widget_type=None, options={})
    147             options["widget_type"] = widget_type
--> 148         wdg_class, opts = get_widget_class(value, annotation, options)
        wdg_class = undefined
        opts = undefined
        get_widget_class = <function get_widget_class at 0x7f4414388ee0>
        value = None
        annotation = ForwardRef('napari.layers.Image')
        options = {}
    149 

~/miniconda3/envs/all/lib/python3.8/site-packages/magicgui/type_map.py in get_widget_class(value=None, annotation=ForwardRef('napari.layers.Image'), options={})
    201     _options = cast(WidgetOptions, options)
--> 202     widget_type, _options = pick_widget_type(value, annotation, _options)
        widget_type = undefined
        _options = {}
        global pick_widget_type = <function pick_widget_type at 0x7f441438baf0>
        value = None
        annotation = ForwardRef('napari.layers.Image')
    203 

~/miniconda3/envs/all/lib/python3.8/site-packages/magicgui/type_map.py in pick_widget_type(value=None, annotation=<class 'napari.layers.image.image.Image'>, options={})
    176     # return widgets.LiteralEvalLineEdit, {}
--> 177     raise ValueError(f"Could not pick widget for type: {dtype!r}")
        global ValueError = undefined
    178 

ValueError: Could not pick widget for type: <class 'napari.layers.image.image.Image'>

The above exception was the direct cause of the following exception:

PluginImportError                         Traceback (most recent call last)
~/miniconda3/envs/all/lib/python3.8/site-packages/napari_plugin_engine/manager.py in discover(self=<napari_plugin_engine.manager.PluginManager object>, path=None, entry_point=None, prefix=None, ignore_errors=True)
    241 
    242             try:
--> 243                 if self._load_and_register(mod_name, name):
        self._load_and_register = <bound method PluginManager._load_and_register of <napari_plugin_engine.manager.PluginManager object at 0x7f4414401700>>
        mod_name = 'napari_plugin_engine'
        name = 'napari_plugin_engine'
    244                     count += 1
    245             except PluginError as e:

~/miniconda3/envs/all/lib/python3.8/site-packages/napari_plugin_engine/manager.py in _load_and_register(self=<napari_plugin_engine.manager.PluginManager object>, mod_name='affinder.plugin', plugin_name='affinder')
    294                 return None
    295         except Exception as exc:
--> 296             raise PluginImportError(
        global PluginImportError = <class 'napari_plugin_engine.exceptions.PluginImportError'>
        plugin_name = 'affinder'
        global cause = undefined
        exc = undefined
    297                 f'Error while importing module {mod_name}',
    298                 plugin_name=plugin_name,

PluginImportError: Error while importing module affinder.plugin
================================================================================
```

**Comment by jni** [comment]
Huh, was it bad syntax highlighting? I could have sworn that class name was not there before! Anyway, it looks interesting:

```pytb
ValueError: Could not pick widget for type: <class 'napari.layers.image.image.Image'>
```

**Comment by tlambert03** [comment]
> Huh, was it bad syntax highlighting? I could have sworn that class name was not there before! Anyway, it looks interesting:
> 
> ```
> ValueError: Could not pick widget for type: <class 'napari.layers.image.image.Image'>
> ```

looks like plugins are getting registered before `register_types_with_magicgui` ... will work on it

**Comment by tlambert03** [comment]
looks like we need to move up the call to `register_types_with_magicgui ` in napari.__init__ and delay the import of `from ..plugins.io import read_data_with_plugins` in `viewer_model.py`

**Comment by tlambert03** [comment]
ok, after https://github.com/napari/napari/pull/2139 you should be good here... however, you need to use `napari_experimental_provide_function_widget` with an _undecorated_ `start_affinder` function, rather than `napari_experimental_provide_dock_widget`

```python
@napari_hook_implementation
def napari_experimental_provide_function_widget():
    return start_affinder, {'call_button': 'Start', 'layout': 'vertical'}
```

the main reason that this can't work with `provide_dock_widget` (even though it feels like it should because you can use it with `add_dock_widget`), is that we need to have a _class_ not a single _instance_ , so that if someone were to add a plugin dock widget, and then delete it, they could still create/instantiate another one if they wanted to.

**Comment by sofroniewn** [comment]
> ok, after napari/napari#2139 you should be good here... however, you need to use napari_experimental_provide_function_widget with an undecorated start_affinder function, rather than napari_experimental_provide_dock_widget

Hmm, interesting, makes sense. I think that's a good thing ultimately, but I'm still hoping one day we can make `napari_experimental_provide_function_widget` accept ReadOnly views, which wouldn't work with this plugin right now, but we'll cross that bridge when we get to it!! Maybe there's a way to make a more magicgui focused hookspec or use annotations that specifically request `ReadOnly` or `Mutable` objects to make it more clear as @tlambert03 suggested on zulip once.

**Comment by tlambert03** [comment]
i'm not sure i'm following what read only views have to do with function_widget vs dock_widget hooks here?

>  a more magicgui focused hookspec

how more magicgui focused than `provide_function_widget`?  If you mean something that can accept an _instance_ of a magicgui widget... I'm not sure I see the merit of that on the plugin side of things (where we really kind of need the abillity to make _more_ of the widgets).  That feels like something that works just fine with `window.add_dock_widget`

**Comment by sofroniewn** [comment]
> i'm not sure i'm following what read only views have to do with function_widget vs dock_widget hooks here?

I guess I've always dreamed of the function hookspec being functional, data comes in, data goes out, and is stateless as much as possible, (i.e. takes ReadOnly views), as this would allow the safe composition of functions in graphs like dimitri/ robert are working on or workflow runners using functions provided by this hooks. Something like this plugin which is connecting events/ adding layers etc doesn't really belong inside a graph or workflow like that as it's interactive which is why I wouldn't have thought it a fit for our "functional" hookspec but our more general "dock widget" hookspec. A workflow builder tool that looked through all the hook-available "functions" and then tried to let users build workflow graphs using the function from this plugin would break if someone tried to use it. Passing `ReadOnly` views would enforce this distinction, but would break this plugin, so if we decide to do that with this hook spec then we'll need to change this, which is why I wanted to mention it here.

> how more magicgui focused than provide_function_widget

Stepping back, maybe a better thing to have said is that I want the `provide_function_widget` to be more `functional` so that we can think about building function based workflows. I see three use cases right now but we only have two hookspecs

1. Complex interactivity, anything goes, custom Qt elements - use `provide_dock_widget`
2. Complex interactivity, anything goes, magicgui widgets - right now possible with `provide_function_widget`
3. Analysis functions, takes in data, outputs data, stateless - also possible with `provide_function_widget`, but no guarantees right now

I think now we're meeting cases (1) and (2) well, but ultimately I'd like us to move towards (2) and (3) as much as possible! It's not clear to me if we need a third hookspec right now or rename things or if there is just a better way to think about it.

Anyway, it is soooo much better to be having these discussions over real examples, and I'm not unhappy with where we are right now, but thought this plugin was an interesting case to discuss, and am curious what everyone else thinks!!

**Comment by tlambert03** [comment]
> I guess I've always dreamed of the function hookspec being functional, data comes in, data goes out, and is stateless as much as possible

i think that's still a very good and achievable goal.  but I think we probably have to differentiate in our minds between _functions_ and _function widgets_.  Widgets are by their very nature stateful (i.e. the second you have a dropdown box that accepts input from the user, you've got state).  There's nothing stopping us from developing a pure analysis functional hookspec, and we should!  It's just that this is not that.

I just see it as two totally different goals.  Something like affinder probably wouldn't ever work in a node graph, it's an interactive plugin that helps the user determine the affine transform, not a pure function that takes inputs and gives outputs.  Different approaches for different goals.

> I want the provide_function_widget to be more functional so that we can think about building function based workflows. I see three use cases right now but we only have two hookspecs

my opinion is probably clear from what I just said, but i think trying to make `provide_function_widget` _be_ the analysis function hookspec that we've always imagined (i.e. number 3) is packing too much into to a single hookspec.  I'm not sure I think those kinds of functions should even be accepted in a hookspec that also accepts `magic_kwargs`.

**Comment by sofroniewn** [comment]
> There's nothing stopping us from developing a pure analysis functional hookspec, and we should! It's just that this is not that.
>
> I just see it as two totally different goals. Something like affinder probably wouldn't ever work in a node graph, it's an interactive plugin that helps the user determine the affine transform, not a pure function that takes inputs and gives outputs. Different approaches for different goals.

Yup, that's the crux of it! It was my original goal when I started https://github.com/napari/napari/pull/1816 - which is why I gave the title of that PR - "Add magicgui hook spec for "functional" plugins"  but that has ended up landing in a different place `provide_function_widget`, and maybe that's ok!!

> my opinion is probably clear from what I just said, but i think trying to make provide_function_widget be the analysis function hookspec that we've always imagined (i.e. number 3) is packing too much into to a single hookspec. I'm not sure I think those kinds of functions should even be accepted in a hookspec that also accepts magic_kwargs.

Ok fair points. We definitely want to be able to generate widgets for these functions using magicgui if we want too, but we might not need those additional `magic_kwargs` - we'd instead force all parameter annotations to be in the function signature and we'd control defaults for other settings.

How would you feel about a new hookspec `napari_experimental_provide_analysis_function` focused on (3) which accepts a callable / list of callables - and either takes readonly copies of napari objects or our data tuples. My hope is that Robert/ Dmity etc. could then use that hookspec. If that sounds reasonable I'll make a new issue on the main repo and we can move discussion there, and leave @jni's affinder repo in peace :-)

**Comment by tlambert03** [comment]
> How would you feel about a new hookspec napari_experimental_provide_analysis_function focused on (3) which accepts a callable / list of callables - and either takes readonly copies of napari objects or our data tuples. My hope is that Robert/ Dmity etc. could then use that hookspec. If that sounds reasonable I'll make a new issue on the main repo and we can move discussion there, and leave @jni's affinder repo in peace :-)

yeah, that was going to be my suggestion to you.  I think the main thing lacking here with "functional plugins" is not the hookspec itself, but a clear idea about what we're even going to do with the thing once somebody gives it to us!  It's great to say "give us a something that accepts X and returns Y" ... but without a clear idea of where we're going to plug it in, it's not immediately clear to what use it is.  For `function_widgets`, you proposed a very clear application in napari/napari#1816 (I just don't think "provide_function" was the right name for what you were proposing 😄 ... it even had magicgui in the PR title, which will always be stateful)

**Comment by sofroniewn** [comment]
>  I think the main thing lacking here with "functional plugins" is not the hookspec itself, but a clear idea about what we're even going to do with the thing once somebody gives it to us! It's great to say "give us a something that accepts X and returns Y" ... but without a clear idea of where we're going to plug it in, it's not immediately clear to what use it is.

I'll make a new issue, but I want note that there is a very much a clear idea of what we would initially do with these functions - they would be accessible in the exact same drop down menu that our other `widget` named hookspecs are and when selected we'd generate magicgui widgets for them.

i.e. the initial behavior of `provide_analysis_function` would be identical to `provide_function_widget`, but just with a more limited API, which would then allow us to work on things like composition graphs and workflow runners that we couldn't do without this, and where we've already got a couple of prototypes in play.

>  For function_widgets, you proposed a very clear application in napari/napari#1816 

The motivating example for 1816 was the `gaussian_blur`. This would be still be achievable via `provide_analysis_function` which would now be the recommended approach for such analysis routines - it is how I would implement my segmentation analysis functions too. The stuff done in `affinder` would not be possible - but that was never in the applications I laid out in 1816.

> (I just don't think "provide_function" was the right name for what you were proposing 😄 ... it even had magicgui in the PR title, which will always be stateful)

This I disagree with. The statefulness of the widget doesn't matter,  it is the statefulness of the function that matters. The widget we can create and take away as desired as we're controlling it and so it's state doesn't matter, the function needs to be stateless though otherwise the graph concept gets very messy. I see no incompatibility with the vision for a graph of image analysis functions and using magicgui to optionally generate widgets even though magicgui is stateful.

**Comment by jni** [comment]
Ok after napari/napari#2139, napari/napari#2143, napari/magicgui#117, and [`4629839` (#12)](https://github.com/jni/affinder/pull/12/commits/4629839ddc2a315c7d3e6ceec959d86fe8dc0da7), this is now fully working! In it goes! 🎉 Thank you @sofroniewn and @tlambert03 for iterating with me on this!

**Pull request merged**
