### PR TITLE
find packages in setup.cfg, fix wheel

### LINKED ISSUE #43: wheel building broken?
in testing out npe2 convert, I realized that `python setup.py bdist_wheel` doesn't seem to be working here.  It's not including the `affinder` module (indeed, the wheel on pypi lacks the actual module) https://pypi.org/project/affinder/#files

I think you need to add `packages = find:` to your `[options]` (see for [example](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html))

```ini
[options]
packages = find:
...
```

fortunately, this _is_ in the cookiecutter! 😅

### PR DESCRIPTION
**Pull request by tlambert03**
closes #43 (sorry, should have just opened a PR to begin with!)

### CODE REVIEW

**Comment by jni** [comment]
@tlambert03 I'm curious why, when using src layout, my tests passed, if I was missing this???

**Comment by tlambert03** [comment]
i assume it builds the sdist, which, interestingly _does_ have this.  there are still some mysteries to me about the differences between wheels and sdists.  but I assume that's at play here

**Comment by jni** [comment]
gdi codecov 🤦 😂

**Comment by jni** [comment]
LOL it literally changed from failing to passing as I wrote that comment!!!

**Pull request merged**
