### PR TITLE
Consider scale and translation in apply_tf

### PR DESCRIPTION
**Pull request by andreasmarnold**
This addresses issue #80

Note: Affine transformations are not inherently commutative so I'm not sure this is universally correct. It seems to work but maybe you know a more elegant solution?

Unfortunately, I didn't quite remember how to do the auto-formatting without having pre-commit...
Also, I'd be very grateful for any feedback on how well I adhered to best-practices in git (correct branch, etc...). I tried but it's all a bit new for me.

I did not change anything in the tests.

### CODE REVIEW

**Comment by jni** [comment]
Hey!

You should generally make a new branch from main and submit a PR from that branch. This is because otherwise your main branch diverges from the one in this project, which makes it harder to update in the future.

It's easy to go back though:

```
git reset HEAD~  # <-- point the main branch to the commit before this one
git switch --create apply-tf-complete  # <-- make a new branch with this name
git commit -a -m "take into account other layer transforms"  # <-- make your commit again, now on correct branch
git push origin --set-upstream apply-tf-complete  # <-- push new branch to your fork
```

Then you can (and should) make a new PR from that branch.

I wrote a git tutorial many years ago — you might find it useful. https://jni.github.io/git-tutorial

As to the rotations etc, you're right, it's tricky, which is why I didn't immediately make a PR to fix things. 😅 But you shouldn't do it the way you've done it, instead we have a utility:

```python
from napari.utils.transforms import CompositeAffine
```

that will take all the initial transforms and apply them for you in the right order, and make a matrix. However, I'm not 100% sure that I want to use it directly, because that means importing from napari. Maybe we can just copy the relevant code over.

PS: Also, after you make the PR you can fix your main branch by doing:

```
git switch main
git pull upstream  # <-- in case I made some changes
git push origin --force-with-lease  # overwrite the remote branch, but only if someone else hasn't changed it since the last time you pushed; not relevant here but good habit compared with --force
```

**Comment by jni** [comment]
I'll close this one because it's going to get borked anyway when you fix your main branch. 😅

**Comment by jni** [comment]
(And of course I'm happy to chat live if you encounter issues with git!)

**Comment by andreasmarnold** [comment]
Hey Juan,
Thanks for the reply!

> git reset HEAD~  # <-- point the main branch to the commit before this one
git switch --create apply-tf-complete  # <-- make a new branch with this name
git commit -a -m "take into account other layer transforms"  # <-- make your commit again, now on correct branch
git push origin --set-upstream apply-tf-complete  # <-- push new branch to your fork

I fixed this but I didn't get around to look into properly applying the transformations yet. I'll make a new PR once I've done some work on that (probably towards the end of this week).

And thanks for the infos on git! Really helpful :)

**Pull request closed without merging**
